const COLOR_NEGRO 		= '#121212';
const COLOR_VERDE_CLARO = '#1BD760';
const COLOR_BLANCO 		= '#FFFFFF';
const COLOR_GRIS_OSCURO = '#2A2A2A';
const COLOR_GRIS 		= '#B3B3B3';


export {
	COLOR_NEGRO,
	COLOR_VERDE_CLARO,
	COLOR_BLANCO,
	COLOR_GRIS_OSCURO,
	COLOR_GRIS
}
